export type Business = {
  'Submission ID': string;
  'Submission Date': string;
  'Last Update Date': string;
  'First Name': string;
  'Last Name': string;
  Company: string;
  'Job Title': string;
  Email: string;
  Mobile: string;
  'Street Address': string;
  'Street Address Line 2': string;
  City: string;
  'State / Province': string;
  'Postal / Zip Code': string;
  Country: string;
  'Your interests': string;
  'Choose the Brand': string;
  'Your QR Generation': string;
};

export type Exhibitor = {
  'Submission ID': string;
  'Submission Date': string;
  'First Name': string;
  'Last Name': string;
  'Company Name': string;
  'Brand Name': string;
  'Number of Branches': string;
  'Street Address': string;
  'Street Address Line 2': string;
  City: string;
  'State / Province': string;
  'Postal / Zip Code': string;
  Country: string;
  Region: string;
  'Mobile Number': string;
  Email: string;
  'Choose your space': string;
};

export type Visitor = {
  'Unique ID': string;
  'Submission ID': string;
  'Submission Date': string;
  Name: string;
  'Company Name': string;
  Occupation: string;
  'Are You': string;
  'Are You 2': string;
  'The sector you are interested in': string;
  'Expected capital': string;
  'Mobile Number': string;
  Email: string;
  'Street Address': string;
  'Street Address Line 2': string;
  City: string;
  'State / Province': string;
  'Postal / Zip Code': string;
  Country: string;
};
